/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC;

import Modelo.Operadores;
import javax.swing.JOptionPane;

/**
 *
 * @author APRENDIZ
 */
public class VistaOperadores extends javax.swing.JFrame {

  public int tipodocumento;
    public int documento;
    public String nombres;
    public String apellidos;
    public String direccion;
    public String correo;
    public String telefono;
    public VistaOperadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdcedula = new javax.swing.JRadioButton();
        rdti = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txfdocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfnombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfapellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfcorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txftelefono = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        txfdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        buttonGroup1.add(rdcedula);
        buttonGroup1.add(rdti);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registrar Operadores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel2.setText("Tipo de documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        rdcedula.setText("Cedula");
        jPanel1.add(rdcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        rdti.setText("Tarjeta Identidad");
        jPanel1.add(rdti, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel3.setText("Documento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel1.add(txfdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, -1));

        jLabel4.setText("Nombres");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        jPanel1.add(txfnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, -1));

        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        jPanel1.add(txfapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 250, -1));

        jLabel6.setText("Correo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel1.add(txfcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 250, -1));

        jLabel7.setText("Telefono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        jPanel1.add(txftelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, -1));

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));
        jPanel1.add(txfdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 250, -1));

        jLabel8.setText("Dirección");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed

     if(rdcedula.isSelected()){
        
        tipodocumento = 1;
        
        }else if(rdti.isSelected()){
        tipodocumento = 2;
        
        }

        try {
            nombres  = txfnombres.getText();
             apellidos = txfapellidos.getText();
             documento = Integer.parseInt(txfdocumento.getText());
             correo = txfcorreo.getText();
             telefono = txftelefono.getText();
             direccion  = txfdireccion.getText();
             
            // Instanciar la clase Agencias y enviar los datos
            Operadores cr = new Operadores();
            cr.create(tipodocumento, nombres, apellidos, documento, correo, telefono, direccion);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en los datos: Verifica los campos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
           


    }//GEN-LAST:event_btnregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOperadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOperadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOperadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOperadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOperadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdcedula;
    private javax.swing.JRadioButton rdti;
    private javax.swing.JTextField txfapellidos;
    private javax.swing.JTextField txfcorreo;
    private javax.swing.JTextField txfdireccion;
    private javax.swing.JTextField txfdocumento;
    private javax.swing.JTextField txfnombres;
    private javax.swing.JTextField txftelefono;
    // End of variables declaration//GEN-END:variables
}
