/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC;

import Modelo.Paquetes;
import javax.swing.JOptionPane;

public class VistaPaquetes extends javax.swing.JFrame {

    /**
     * Creates new form Paquetes
     */
    public VistaPaquetes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfdestino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txforigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txffechaventa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfhorasalida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txffechaejecucion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfobservaciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfidcliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txfidagencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txfidmedio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txfidoperador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txfmatricula = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txfpreciopax = new javax.swing.JTextField();
        btnenviar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txfhoraventa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registrar Paquetes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setText("Id del Destino");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jPanel1.add(txfdestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 300, -1));

        jLabel3.setText("Id del Origen");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        jPanel1.add(txforigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 300, -1));

        jLabel4.setText("Fecha de venta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(txffechaventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 300, -1));

        jLabel5.setText("Hora de salida");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        jPanel1.add(txfhorasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 300, -1));

        jLabel6.setText("Fecha de Ejecucion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel1.add(txffechaejecucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 300, -1));

        jLabel7.setText("Observaciones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel1.add(txfobservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 300, -1));

        jLabel8.setText("Id del Cliente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        jPanel1.add(txfidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 300, -1));

        jLabel9.setText("Id de la agencia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel1.add(txfidagencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 300, -1));

        jLabel10.setText("Id del medio");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jPanel1.add(txfidmedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 300, -1));

        jLabel11.setText("id Operador");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        jPanel1.add(txfidoperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 300, -1));

        jLabel12.setText("Matricula Vehiculo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));
        jPanel1.add(txfmatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 300, -1));

        jLabel13.setText("Precio del paquete");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));
        jPanel1.add(txfpreciopax, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 300, -1));

        btnenviar.setText("Registrar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel15.setText("Hora de venta");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));
        jPanel1.add(txfhoraventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed


try {
    // Capturar datos desde los campos de texto
        int idDestino = Integer.parseInt(txfdestino.getText());
    int idOrigen = Integer.parseInt(txforigen.getText());
    String fechaVenta = txffechaventa.getText();
    String horaVenta = txfhoraventa.getText();
    String horaSalida = txfhorasalida.getText();
    String fechaEjecucion = txffechaejecucion.getText();
    String observacion = txfobservaciones.getText();
    int idCliente = Integer.parseInt(txfidcliente.getText());
    int idAgencia = Integer.parseInt(txfidagencia.getText());
    int idMedio = Integer.parseInt(txfidmedio.getText());
    int idOperadores = Integer.parseInt(txfidoperador.getText());
    String matricula = txfmatricula.getText();
    String precios = txfpreciopax.getText();

    // Instanciar la clase Operadores y enviar los datos
    Paquetes cr = new Paquetes();
cr.create(idDestino, idOrigen, fechaVenta, horaVenta, horaSalida, fechaEjecucion, 
              observacion, idCliente, idAgencia, idMedio, idOperadores, matricula, precios);

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Error en los datos: Verifica los campos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_btnenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPaquetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txfdestino;
    private javax.swing.JTextField txffechaejecucion;
    private javax.swing.JTextField txffechaventa;
    private javax.swing.JTextField txfhorasalida;
    private javax.swing.JTextField txfhoraventa;
    private javax.swing.JTextField txfidagencia;
    private javax.swing.JTextField txfidcliente;
    private javax.swing.JTextField txfidmedio;
    private javax.swing.JTextField txfidoperador;
    private javax.swing.JTextField txfmatricula;
    private javax.swing.JTextField txfobservaciones;
    private javax.swing.JTextField txforigen;
    private javax.swing.JTextField txfpreciopax;
    // End of variables declaration//GEN-END:variables
}
