/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC;

import Controlador.Conexiones;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author APRENDIZ
 */
public class VistaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuarios
     */
    public VistaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvisor = new javax.swing.JTable();
        btnClientes = new javax.swing.JButton();
        btnvehiculos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblvisor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblvisor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1420, -1));

        btnClientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVC/10729125.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClientes.setRolloverEnabled(false);
        btnClientes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 90, 80));

        btnvehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVC/2555021.png"))); // NOI18N
        btnvehiculos.setText("Vehiculos");
        btnvehiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvehiculos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnvehiculos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnvehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvehiculosActionPerformed(evt);
            }
        });
        jPanel1.add(btnvehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 90, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        mostrarClientes("tblclientes");


    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnvehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvehiculosActionPerformed

        mostrarVehiculos("tblvehiculo");
        
    }//GEN-LAST:event_btnvehiculosActionPerformed

    public void mostrarVehiculos(String tabla){
    
String sql = "SELECT * FROM " + tabla;
Statement st;
Conexiones con = new Conexiones();
Connection conexion = con.conectarBD();

if (conexion == null) {
    JOptionPane.showMessageDialog(null, "Error: No se pudo conectar a la base de datos.");
    return;
}

// Definir modelo de la tabla con los nuevos campos
DefaultTableModel model = new DefaultTableModel();
model.addColumn("Matrícula");
model.addColumn("Marca");
model.addColumn("Puestos");
model.addColumn("Modelo");
model.addColumn("Número de Motor");
model.addColumn("Categoría");
model.addColumn("ID Tipo");
model.addColumn("ID Promotores");
tblvisor.setModel(model);

String[] datos = new String[8];

try {
    st = conexion.createStatement();
    ResultSet rs = st.executeQuery(sql);

    while (rs.next()) {
        datos[0] = rs.getString("matricula");
        datos[1] = rs.getString("marca");
        datos[2] = String.valueOf(rs.getInt("puestos")); // Convertir int a String
        datos[3] = rs.getString("modelo");
        datos[4] = String.valueOf(rs.getInt("numeromotor")); // Convertir int a String
        datos[5] = rs.getString("categoria");
        datos[6] = String.valueOf(rs.getInt("idtipo")); // Convertir int a String
        datos[7] = String.valueOf(rs.getInt("idpromotores")); // Convertir int a String

        model.addRow(datos);
    }

    rs.close();
    st.close();
    conexion.close(); // Cierra la conexión después de usarla.

    tblvisor.setModel(model); // Mueve la asignación aquí después de llenar los datos.

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.toString());
}

        
    }
    
    
    
    public void mostrarClientes(String tabla) {

        String sql = "SELECT * FROM " + tabla;
        Statement st;
        Conexiones con = new Conexiones();
        Connection conexion = con.conectarBD();

        if (conexion == null) {
            JOptionPane.showMessageDialog(null, "Error: No se pudo conectar a la base de datos.");
            return;
        }

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("tipodocumento");
        model.addColumn("documento");
        model.addColumn("nombres");
        model.addColumn("apellidos");
        model.addColumn("Eps");
        model.addColumn("alergias");
        model.addColumn("fecha de nacimiento");
        model.addColumn("correo");
        model.addColumn("estado civil");
        model.addColumn("telefono");
        model.addColumn("direccion");
        tblvisor.setModel(model);

        String[] datos = new String[12];

        try {
            st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString(1);
                String tipoDocumento = rs.getString(2);
                if (tipoDocumento.equals("1")) {
                    datos[1] = "Cédula";
                } else if (tipoDocumento.equals("2")) {
                    datos[1] = "Tarjeta de Identidad";
                } else {
                    datos[1] = "Otro"; // En caso de que haya otro tipo de documento
                }
                datos[2] = rs.getString(12);
                datos[3] = rs.getString(3);
                datos[4] = rs.getString(4);
                datos[5] = rs.getString(5);
                datos[6] = rs.getString(6);
                datos[7] = rs.getString(7);
                datos[8] = rs.getString(8);
                datos[9] = rs.getString(9);
                datos[10] = rs.getString(10);
                datos[11] = rs.getString(11);
                model.addRow(datos);
            }

            rs.close();
            st.close();
            conexion.close(); // Cierra la conexión después de usarla.

            tblvisor.setModel(model); // Mueve la asignación aquí después de llenar los datos.

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnvehiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblvisor;
    // End of variables declaration//GEN-END:variables
}
